{{- $platform := "bmrg" -}}
{{- $product := "bosun" -}}
{{- $tier := "config" -}}
{{- $values := .Values -}}
{{- $context := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "tier" $tier ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier ) | nindent 4 }}
data:
  application.properties: |
    server.port=8080
    spring.data.mongodb.uri=mongodb://{{ $values.global.database.mongodb.user }}:${MONGODB_PASSWORD}@{{ $values.global.database.mongodb.host }}{{ if $values.global.database.mongodb.port }}:{{ $values.global.database.mongodb.port }}{{ end }}/{{ $values.global.database.mongodb.database }}{{ if $values.global.database.mongodb.args }}?{{ $values.global.database.mongodb.args }}{{ end }}
    {{- range $k, $v := $values.services }}
    boomerang.bosun.service.{{ $k }}.host={{- include "bmrg.name" (dict "context" $context "tier" "services" "component" $k ) }}
    boomerang.bosun.service.{{ $k }}.root={{ default "" $values.global.ingress.root }}/services/{{ $k }}
    {{- end }}
    {{ include "bmrg.core.services" $context | indent 4 }}
    boomerang.cicd.service.ci.host=bmrg-cicd-services-ci
    opa.host={{- include "bmrg.name" (dict "context" $context "tier" "opa") }}
    {{- if $values.general.enable.debug }}
    logging.level.org.springframework.web.client.RestTemplate=DEBUG
    logging.level.org.springframework.core.env.PropertySourcesPropertyResolver=DEBUG
    logging.level.root=INFO
    {{- end }}
    swagger.enable={{ $values.general.enable.apidocs }}
    boomerang.environment={{ .Release.Namespace }}
    boomerang.standalone={{ $values.general.enable.standalone }}
    proxy.enable={{ $values.proxy.enable }}
    {{- if $values.proxy.enable }}
    proxy.host={{ $values.proxy.host }}
    proxy.port={{ $values.proxy.port }}
    proxy.ignore={{ $values.proxy.ignore }}
    {{- if $values.monitoring.newrelic.enable }}
    newrelic.config.common.proxy_host={{ $values.proxy.host }}
    newrelic.config.common.proxy_port={{ $values.proxy.port }}
    newrelic.config.proxy_host={{ $values.proxy.host }}
    newrelic.config.proxy_port={{ $values.proxy.port }}
    {{- end }}
    {{- end }}
    {{- if $values.monitoring.newrelic.enable }}
    newrelic.config.distributed_tracing.enabled=true
    {{- end }}
    xray.url.api.base={{ $values.xray.url }}
    xray.boomerang.user={{ $values.xray.user }}
    xray.boomerang.apitoken={{ $values.xray.token }}
    sonarqube.url.api.base={{ $values.sonarqube.url }}
    sonarqube.apitoken={{ $values.sonarqube.token }}
