{{- $platform := "bmrg" -}}
{{- $product := "bosun" -}}
{{- $tier := "opa" -}}
{{- $context := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "tier" $tier ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier ) | nindent 4 }}
data:
  config.yaml: |
    services:
      - name: bosun
        url: http://{{- include "bmrg.name" (dict "context" $context "tier" "services" "component" "policy" ) }}/internal
    bundles:
      bosun:
        service: bosun
        resource: bundle.tar.gz
        polling:
          min_delay_seconds: 60
          max_delay_seconds: 300