{{- $platform := "bmrg" -}}
{{- $product := "bosun" -}}
{{- $tier := "opa" -}}
{{- $values := .Values -}}
{{- $context := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "tier" $tier ) }}
  labels:
    name: {{ include "bmrg.name" (dict "context" $context "tier" $tier ) }}
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier ) | nindent 4 }}
spec:
  replicas: {{ $values.opa.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "bmrg.name" (dict "context" $context "tier" $tier ) }}
      {{- include "bmrg.labels.standard" (dict "context" $context "platform" $platform "product" $product "tier" $tier "zone" $values.opa.zone ) | nindent 6 }}
  template:
    metadata:
      labels:
        name: {{ include "bmrg.name" (dict "context" $context "tier" $tier ) }}
        {{- include "bmrg.labels.standard" (dict "context" $context "platform" $platform "product" $product "tier" $tier "zone" $values.opa.zone ) | nindent 8 }}
    spec:
      containers:
        - name: "{{ $tier }}-cntr"
          image: "{{ $values.opa.image.repository }}:{{ $values.opa.image.tag }}"
          imagePullPolicy: {{ $values.image.pullPolicy }}
          ports:
          - name: {{ $platform }}-port-cntr
            containerPort: 8181
            protocol: TCP
          args:
          - "run"
          - "--ignore=.*"
          - "--server"
          - "--config-file"
          - "/config/config.yaml"
          volumeMounts:
          - readOnly: true
            mountPath: "/config"
            name: policy-config
          livenessProbe:
            httpGet:
              scheme: HTTP
              port: 8181
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health?bundle=true
              scheme: HTTP
              port: 8181
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
      - name: policy-config
        configMap:
          name: {{ include "bmrg.name" (dict "context" $context "tier" $tier ) }}