{{- $platform := "bmrg" -}}
{{- $product := "bosun" -}}
{{- $tier := "util" -}}
{{- $component := "data" -}}
{{- $context := . -}}
{{- if $.Values.job.data.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "tier" $tier "component" $component ) }}
  labels:
    name: {{ include "bmrg.name" (dict "context" $context "tier" $tier "component" $component ) }}
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier "component" $component ) | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  backoffLimit: 1
  completions: 1
  template:
    metadata:
      labels:
        name: {{ include "bmrg.name" (dict "context" $context "tier" $tier "component" $component ) }}
        {{- include "bmrg.labels.standard" (dict "context" $context "platform" $platform "product" $product "tier" $tier "component" $component ) | nindent 8 }}
    spec:
      containers:
        - name: "pre-install-{{ $tier }}-cntr"
          image: "{{ .Values.image.registry }}{{ .Values.job.data.image.repository }}:{{ .Values.job.data.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
          - name: JAVA_OPTS
            value: "-Dspring.profiles.active={{ $.Values.job.data.profile }} -Dspring.data.mongodb.uri=mongodb://{{ $.Values.global.database.mongodb.user }}:{{ if $.Values.global.database.mongodb.secretName }}${MONGODB_PASSWORD}{{ else }}{{ $.Values.global.database.mongodb.password }}{{ end }}@{{ $.Values.global.database.mongodb.host }}:{{ $.Values.global.database.mongodb.port }}/boomerang"
          {{- if $.Values.global.database.mongodb.secretName }}
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.global.database.mongodb.secretName }}
                key: mongodb-password
          {{- end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      restartPolicy: Never
{{- end }}