{{- $platform := "bmrg" -}}
{{- $product := "bosun" -}}
{{- $tier := "service" -}}
{{- $values := .Values -}}
{{- $context := . -}}
{{- if $.Values.global.ingress.enabled -}}
{{- range $k, $v := $.Values.service }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "tier" $tier "component" $k ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier "component" $k ) | nindent 4 }}
  annotations:
    {{- if eq $.Values.global.auth.enabled true }}
    {{- include "bmrg.ingress.config.auth_proxy_auth_annotations.global" $ | nindent 4 }}
    {{- end }}
    {{ $.Values.global.ingress.annotationsPrefix}}/configuration-snippet: |
      {{- if eq $.Values.global.auth.enabled true }}
      {{- include "bmrg.ingress.config.auth_proxy_access_control" $ | nindent 6 }}
      {{- include "bmrg.ingress.config.auth_proxy_authorization" $ | nindent 6 }}
      {{- end }}
      if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' $http_origin;
      add_header 'Access-Control-Allow-Credentials' 'true';
      add_header 'Access-Control-Allow-Methods' 'GET,POST,PUT,PATCH,DELETE,OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Length' 0;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      return 204;}
    {{ $.Values.global.ingress.annotationsPrefix}}/ssl-redirect: "false"
    {{ $.Values.global.ingress.annotationsPrefix}}/rewrite-target: /{{ $k }}/$2
    {{ $.Values.global.ingress.annotationsPrefix}}/client-max-body-size: 1m
    kubernetes.io/ingress.class: {{ $.Values.global.ingress.class}}
spec:
  rules:
    - host: {{ $values.global.ingress.host }}
      http:
        paths:
          - path: {{ default "" $values.global.ingress.root }}/{{ $tier }}/{{ $k }}(/|$)(.*)
            backend:
              serviceName:  {{ include "bmrg.name" (dict "context" $context "tier" $tier "component" $k ) }}
              servicePort: {{ $platform }}-port-svc
  tls:
    - hosts:
        - {{ $values.global.ingress.host }}
      {{- if $values.global.ingress.tlsSecretName }}
      secretName: {{ $values.global.ingress.tlsSecretName }}
      {{- end }}
---
{{- end }}
{{- end }}