{{- $platform := "bmrg" -}}
{{- $product := "bosun" -}}
{{- $tier := "web" -}}
{{- $values := .Values -}}
{{- $context := . -}}
{{- if $.Values.global.ingress.enabled -}}
{{- range $k, $v := $.Values.web }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "tier" $tier "component" $k ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier "component" $k ) | nindent 4 }}
  annotations:
    {{- if eq $.Values.global.auth.enabled true }}
    {{- include "bmrg.ingress.config.auth_proxy_auth_annotations.global" $ | nindent 4 }}
    {{ $.Values.global.ingress.annotationsPrefix}}/configuration-snippet: |
      {{- include "bmrg.ingress.config.auth_proxy_access_control" $ | nindent 6 }}
      {{- include "bmrg.ingress.config.auth_proxy_authorization" $ | nindent 6 }}
    {{- end }}
    {{ $.Values.global.ingress.annotationsPrefix}}/ssl-redirect: "true"
    {{ $.Values.global.ingress.annotationsPrefix}}/client-max-body-size: 1m
    kubernetes.io/ingress.class: {{ $.Values.global.ingress.class}}
spec:
  rules:
    - host: {{ $values.global.ingress.host }}
      http:
        paths:
          - path: {{ default "" $values.global.ingress.root }}/{{ $tier }}/{{ $k }}
            backend:
              serviceName: {{ include "bmrg.name" (dict "context" $context "tier" $tier "component" $k ) }}
              servicePort: {{ $platform }}-port-svc
  tls:
    - hosts:
        - {{ $values.global.ingress.host }}
      {{- if $values.global.ingress.tlsSecretName }}
      secretName: {{ $values.global.ingress.tlsSecretName }}
      {{- end }}
---
{{- end }}
{{- end }}