apiVersion: v2
name: bmrg-flow
description: Boomerang Flow
type: application
version: 4.9.6
appVersion: 3.4.0
home: https://useboomerang.io
dependencies:
  - name: bmrg-common
    repository: https://raw.githubusercontent.com/boomerang-io/charts/index
    version: 3.0.2
    alias: ch
keywords:
- boomerang
- flow
- workflows
