# Default values for bmrg-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# General Configuration
general:
  namePrefix: bmrg-flow
  enable:
    apidocs: false
    debug: false
  externalUrl:
    teams:
    users:
    navigation:
    headerNavigation:

workers:
  security:
    enable: true
    policy: ibm-privileged-psp
  logging:
    type: default
    host:
    port:
    secret:
  nodeSelector:
    #node-role.kubernetes.io/bmrg-worker: true
  tolerations:
  # - key: dedicated
  #   value: bmrg-worker
  #   operator: Equal
  #   effect: NoSchedule

core:
  namePrefix: bmrg-core
  ingressRoot: ""

# General Image Configuration
image:
  registry: boomerangio
  pullPolicy: IfNotPresent
  pullSecret:

# Job Configuraiton
job:
  data:
    enabled: true
    profile: flow
    image:
      repository: /flow-loader
      tag: 0.5.9

# App Configuration
apps:
  flow:
    image:
      repository: /flow-client-web
      tag: 3.9.12
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
    resources:
      requests:
        memory: "100Mi"

# Micro Service Configuration
# Note: There are if conditions in the template referencing the service name i.e. urbancode
services:
  controller:
    image:
      repository: /flow-service-controller
      tag: 6.6.2
    replicaCount: 1
    service:
      type: ClusterIP
    serviceAccount: null
    zone: semi-trusted
    resources:
      requests:
        memory: "512Mi"
  listener:
    image:
      repository: /flow-service-listener
      tag: 2.2.0
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  workflow:
    image:
      repository: /flow-service-workflow
      tag: 3.4.71
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
    resources:
      requests:
        memory: "1Gi"

# Global configuration. This can be overriden by a parent chart.
global:
  database:
    mongodb:
      host: bmrg-mdb001-ibm-mongodb-dev
      port: 27017
      database: boomerang
      args:
      user: boomerang
      password: passw0rd
      secretName:
      tlsSecretName:
  ingress:
    enabled: false
    root: /flow
    host: cloud.boomerangplatform.net
    tlsSecretName: bmrg-tls-cloud
    # The prefix for the annotations inside the ingress definition.
    annotationsPrefix: "nginx.ingress.kubernetes.io"
    # The class of the ingress, it is used to mark the ingress resources to be picked-up by a specific
    # controller.
    class: "nginx"
    # Enable appRoot if you wish the 'app-root' i.e. '/' ingress annotation to redirect to the flow app
    enableAppRoot: false
  auth:
    enabled: false
    mode: basic
    serviceName: bmrg-auth-proxy
    namespace: bmrg-core
    prefix: /oauth
    tokenURL: http://bmrg-core-services-auth.bmrg-core.svc.cluster.local/auth/token/validate/external
    signOutRedirect:

hostAliases: []

proxy:
  enable: false
  host:
  port:

monitoring:
  instana:
    enable: false
    browser:
      reportingUrl:
      key:
  newrelic:
    enable: false
    apm:
      name: Boomerang Private
      key:
      image:
        registry: boomerangio
        repository: /util-newrelicjavaagent
        tag: 5.14.0
    browser:
      id:
      key:
  jaeger:
    enabled: false
    namespace:
    agent:
      host: jaeger-dev-agent
      port: 6831
    collector:
      host: jaeger-dev-collector
      port: 14268
    remoteControlledSampler:
      host: jaeger-dev-agent
      port: 5778

# Eventing related values
eventing:
  enabled: false
  natsUrls: nats://bmrg-dev-nats:4222

tekton:
  enabled: true

auth2proxy:
  enabled: true
