# Default values for bmrg-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# General Configuration
general:
  namePrefix: bmrg-flow
  enable:
    apidocs: false
    debug: false
  externalUrl:
    teams:
    users:
    navigation:
    headerNavigation:

workers:
  security:
    enable: true
    policy: ibm-privileged-psp
  logging:
    type: default
    host:
    port:
    secret:
  nodeSelector:
    #node-role.boomerang.io/tasks: true
  tolerations:
  # - key: dedicated
  #   value: tasks
  #   operator: Equal
  #   effect: NoSchedule

core:
  namePrefix: bmrg-core
  ingressRoot: ""

# General Image Configuration
image:
  registry: boomerangio
  pullPolicy: IfNotPresent
  pullSecret:

# Job Configuraiton
job:
  data:
    enabled: true
    profile: flow
    image:
      repository: /flow-loader
      tag: 1.0.0-beta.21

# App Configuration
apps:
  flow:
    image:
      repository: /flow-client-web
      tag: 3.9.12
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
    resources:
      requests:
        memory: "64Mi"

# Micro Service Configuration
# Note: There are if conditions in the template referencing the service name i.e. urbancode
services:
  handler:
    image:
      repository: /flow-service-handler
      tag: 7.0.0-beta.11
    replicaCount: 1
    service:
      type: ClusterIP
    serviceAccount: null
    zone: semi-trusted
    resources:
      requests:
        memory: "256Mi"
  engine:
    image:
      repository: /flow-service-engine
      tag: 1.0.0-beta.18
    replicaCount: 1
    service:
      type: ClusterIP
    zone: semi-trusted
    resources:
      requests:
        memory: "512Mi"
  workflow:
    image:
      repository: /flow-service-workflow
      tag: 4.0.0-beta.2
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
    resources:
      requests:
        memory: "512Mi"

# Global configuration. This can be overriden by a parent chart.
global:
  database:
    mongodb:
      host: mongodb
      port: 27017
      database: boomerang
      args:
      user: boomerang
      password: passw0rd
      secretName: mongodb
      secretKey: mongodb-password
      tlsSecretName:
  ingress:
    enabled: false
    root: /flow
    host: host.example.io
    tlsSecretName: bmrg-tls-cloud
    # The prefix for the annotations inside the ingress definition.
    annotationsPrefix: "nginx.ingress.kubernetes.io"
    # The class of the ingress, it is used to mark the ingress resources to be picked-up by a specific
    # controller.
    class: "nginx"
    # Enable appRoot if you wish the 'app-root' i.e. '/' ingress annotation to redirect to the flow app
    enableAppRoot: false
  auth:
    enabled: false
    mode: basic
    serviceName: bmrg-auth-proxy
    namespace: bmrg-core
    prefix: /oauth
    tokenURL: http://bmrg-core-services-auth.bmrg-core.svc.cluster.local/auth/token/validate/external
    signOutRedirect:

hostAliases: []

proxy:
  enable: false
  host:
  port:

monitoring:
  instana:
    enable: false
    browser:
      reportingUrl:
      key:
  newrelic:
    enable: false
    apm:
      name: Boomerang Private
      key:
      image:
        registry: boomerangio
        repository: /util-newrelicjavaagent
        tag: 5.14.0
    browser:
      id:
      key:
  jaeger:
    enabled: false
    namespace:
    agent:
      host: jaeger-dev-agent
      port: 6831
    collector:
      host: jaeger-dev-collector
      port: 14268
    remoteControlledSampler:
      host: jaeger-dev-agent
      port: 5778

# Eventing related values
eventing:
  enabled: true
  sinkUrls: 

auth2proxy:
  enabled: true
