# This is a YAML-formatted file.
# Declare variables, and default values, to be passed into your templates.

#General Configuration
general:
  namePrefix: bmrg-bosun
  enable:
    apidocs: false
    debug: false
    standalone: true

#Boomerang Integrations
#Needed if general.enable.standalone=false
core:
  namePrefix: bmrg-core
  namespace: #needed if installed in different namespace
  ingressRoot:
boomerang:
  cicd:
    namePrefix: bmrg-cicd
    namespace: #needed if installed in different namespace

# General Image Configuration
image:
  registry: boomerangio
  pullPolicy: IfNotPresent
  pullSecret:

# Job Configuraiton
job:
  data:
    enabled: true
    profile: bosun
    image:
      repository: /bosun-loader
      tag: 0.1.1

# Web App Configuration
apps:
  bosun:
    image:
      repository: /bosun-client-web
      tag: 0.3.0
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted

# Micro Service Configuration
# Note: There are if conditions in the template referencing the service name i.e. urbancode
services:
  policy:
    image:
      repository: /bosun-service-policy
      tag: 2.5.4
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  repository:
    image:
      repository: /bosun-service-repository
      tag: 0.1.3
    replicaCount: 1
    service:
      type: ClusterIP
    zone: semi-trusted

opa:
  image:
    repository: openpolicyagent/opa
    tag: 0.13.5
  replicaCount: 1
  service:
    type: ClusterIP
  zone: trusted

# Global configuration. This can be overriden by a parent chart.
global:
  database:
    mongodb:
      host: bmrg-mdb001-ibm-mongodb-dev
      port: 27017
      database: boomerang
      args:
      user: boomerang
      password: passw0rd
      secretName:
      tlsSecretName:
  ingress:
    enabled: true
    root: /bosun
    host: cloud.boomerangplatform.net
    tlsSecretName: bmrg-tls-cloud
    # The prefix for the annotations inside the ingress definition. Typically for IKS Community Ingress
    # you need to set it to "nginx.global.ingress.kubernetes.io"
    annotationsPrefix: "ingress.kubernetes.io"
    # The class of the ingress, it is used to mark the ingress resources to be picked-up by a specific
    # controller. For IKS Community Ingress set it to "public-iks-k8s-nginx"
    class: "nginx"
    pathType: ImplementationSpecific
  auth:
    enabled: false
    mode: basic
    serviceName: bmrg-auth-proxy
    namespace: bmrg-core
    prefix: /oauth
    tokenURL: http://bmrg-core-services-auth.bmrg-core.svc.cluster.local/auth/token/validate/external
    signOutRedirect:

hostAliases: []

proxy:
  enable: false
  host:
  port:
  ignore:

monitoring:
  instana:
    enable: false
    browser:
      reportingUrl:
      key:
  newrelic:
    enable: false
    apm:
      name: Boomerang Private
      key:
      image:
        registry: boomerangio
        repository: /util-newrelicjavaagent
        tag: 5.14.0
    browser:
      id:
      key:

# Integration to XRay. Only needed in Standalone mode.
xray:
  token:
  url:
  user:

# Integration to Sonarqube. Only needed in Standalone mode.
sonarqube:
  token:
  url:
