{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "apis" -}}
{{- $values := .Values -}}
{{- $context := . -}}
{{- $apiV1 := false -}}
{{- $apiVersion := "extensions/v1beta1" -}}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
{{- $apiVersion = "networking.k8s.io/v1" -}}
{{- $apiV1 = true -}}
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
{{- $apiVersion = "networking.k8s.io/v1beta1" -}}
{{- end }}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "tier" $tier ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier ) | nindent 4 }}
  annotations:
    {{ $.Values.global.ingress.annotationsPrefix}}/ssl-redirect: "false"
    {{ $.Values.global.ingress.annotationsPrefix}}/rewrite-target: /{{ $tier }}/$2
    {{ $.Values.global.ingress.annotationsPrefix}}/client-max-body-size: 1m
    {{ $.Values.global.ingress.annotationsPrefix}}/limit-rpm: "100"
    {{ $.Values.global.ingress.annotationsPrefix}}/limit-connections: "3"
    {{ $.Values.global.ingress.annotationsPrefix}}/use-regex: "true"
spec:
  ingressClassName: {{ $.Values.global.ingress.class}}
  rules:
    - host: {{ $.Values.global.ingress.host }}
      http:
        paths:
          - path: {{ if $.Values.global.ingress.root }}{{ $.Values.global.ingress.root }}{{- end }}/{{ $tier }}(/|$)(.*)
            {{- if $apiV1 }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "bmrg.name" (dict "context" $context "tier" "services" "component" "workflow" ) }}
                port:
                  name: {{ $platform }}-port-svc
            {{- else }}
            backend:
              serviceName:  {{ include "bmrg.name" (dict "context" $context "tier" "services" "component" "workflow" ) }}
              servicePort: {{ $platform }}-port-svc
            {{- end }}
  tls:
    - hosts:
        - {{ $.Values.global.ingress.host }}
      {{- if $.Values.global.ingress.tlsSecretName }}
      secretName: {{ $.Values.global.ingress.tlsSecretName }}
      {{- end }}