{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "apis" -}}
{{- $values := .Values -}}
{{- $context := . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "tier" $tier ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier ) | nindent 4 }}
  annotations:
    {{ $.Values.global.ingress.annotationsPrefix}}/ssl-redirect: "false"
    {{ $.Values.global.ingress.annotationsPrefix}}/rewrite-target: /{{ $tier }}/$2
    {{ $.Values.global.ingress.annotationsPrefix}}/client-max-body-size: 1m
    {{ $.Values.global.ingress.annotationsPrefix}}/limit-rpm: "100"
    {{ $.Values.global.ingress.annotationsPrefix}}/limit-connections: "3"
    {{ $.Values.global.ingress.annotationsPrefix}}/use-regex: "true"
spec:
  ingressClassName: {{ $.Values.global.ingress.class}}
  rules:
    - host: {{ $.Values.global.ingress.host }}
      http:
        paths:
          - path: {{ if $.Values.global.ingress.root }}{{ $.Values.global.ingress.root }}{{- end }}/{{ $tier }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "bmrg.name" (dict "context" $context "tier" "services" "component" "workflow" ) }}
                port:
                  name: {{ $platform }}-port-svc
  tls:
    - hosts:
        - {{ $.Values.global.ingress.host }}
      {{- if $.Values.global.ingress.tlsSecretName }}
      secretName: {{ $.Values.global.ingress.tlsSecretName }}
      {{- end }}