{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "apps" -}}
{{- $values := .Values -}}
{{- $context := . -}}
{{- if $.Values.global.ingress.enabled -}}
{{- $apiV1 := false -}}
{{- $apiVersion := "extensions/v1beta1" -}}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
{{- $apiVersion = "networking.k8s.io/v1" -}}
{{- $apiV1 = true -}}
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
{{- $apiVersion = "networking.k8s.io/v1beta1" -}}
{{- end }}
{{- range $k, $v := $values.apps }}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "tier" $tier "component" $k ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier "component" $k ) | nindent 4 }}
  annotations:
  annotations:
    {{- if eq $.Values.global.auth.enabled true }}
    {{- include "bmrg.ingress.config.auth_proxy_auth_annotations.global" $ | nindent 4 }}
    {{ $.Values.global.ingress.annotationsPrefix}}/configuration-snippet: |
      {{- include "bmrg.ingress.config.auth_proxy_access_control" $ | nindent 6 }}
      {{- include "bmrg.ingress.config.auth_proxy_authorization" $ | nindent 6 }}
      {{- include "bmrg.ingress.config.auth_proxy_user_email" $ | nindent 6 }}
    {{- end }}
    {{ $.Values.global.ingress.annotationsPrefix}}/ssl-redirect: "true"
    {{ $.Values.global.ingress.annotationsPrefix}}/client-max-body-size: 1m
    kubernetes.io/ingress.class: {{ $.Values.global.ingress.class}}
spec:
  rules:
    - host: {{ $.Values.global.ingress.host }}
      http:
        paths:
          - path: {{ default "" $.Values.global.ingress.root }}/{{ $tier }}/{{ $k }}
            {{- if $apiV1 }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "bmrg.name" (dict "context" $context "tier" $tier "component" $k ) }}
                port:
                  number: {{ $platform }}-port-svc
            {{- else }}
            backend:
              serviceName: {{ include "bmrg.name" (dict "context" $context "tier" $tier "component" $k ) }}
              servicePort: {{ $platform }}-port-svc
            {{- end }}
  tls:
    - hosts:
        - {{ $.Values.global.ingress.host }}
      {{- if $.Values.global.ingress.tlsSecretName }}
      secretName: {{ $.Values.global.ingress.tlsSecretName }}
      {{- end }}
---
{{- end }}
{{- end }}
