{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "services" -}}
{{- $values := .Values -}}
{{- $context := . -}}
{{- if $.Values.global.ingress.enabled -}}
{{- range $k, $v := $values.services }}
{{- if and (ne $k "controller") (ne $k "listener") }}
apiVersion: {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}extensions/v1beta1{{ else }}networking.k8s.io/v1{{ end }}
kind: Ingress
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "tier" $tier "component" $k ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier "component" $k ) | nindent 4 }}
  annotations:
    {{- if eq $.Values.global.auth.enabled true }}
    {{- include "bmrg.ingress.config.auth_proxy_auth_annotations.global" $ | nindent 4 }}
    {{- end }}
    {{- if eq $k "workflow" }}
    {{ $.Values.global.ingress.annotationsPrefix}}/proxy-connect-timeout: "600"
    {{- end }}
    {{ $.Values.global.ingress.annotationsPrefix}}/configuration-snippet: |
      {{- if $.Values.global.auth.enabled }}
      {{- include "bmrg.ingress.config.auth_proxy_access_control" $ | nindent 6 }}
      {{- include "bmrg.ingress.config.auth_proxy_authorization" $ | nindent 6 }}
      {{- include "bmrg.ingress.config.auth_proxy_user_email" $ | nindent 6 }}
      {{- end }}
      if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' $http_origin;
      add_header 'Access-Control-Allow-Credentials' 'true';
      add_header 'Access-Control-Allow-Methods' 'GET,POST,PUT,PATCH,DELETE,OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Length' 0;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      return 204;}
    {{ $.Values.global.ingress.annotationsPrefix}}/ssl-redirect: "false"
    {{ $.Values.global.ingress.annotationsPrefix}}/rewrite-target: /{{ $k }}/$2
    {{ $.Values.global.ingress.annotationsPrefix}}/client-max-body-size: 1m
    kubernetes.io/ingress.class: {{ $.Values.global.ingress.class}}
spec:
  rules:
    - host: {{ $.Values.global.ingress.host }}
      http:
        paths:
          - path: {{ if $.Values.global.ingress.root }}{{ $.Values.global.ingress.root }}{{- end }}/{{ $tier }}/{{ $k }}(/|$)(.*)
            backend:
              serviceName:  {{ include "bmrg.name" (dict "context" $context "tier" $tier "component" $k ) }}
              servicePort: {{ $platform }}-port-svc
  tls:
    - hosts:
        - {{ $.Values.global.ingress.host }}
      {{- if $.Values.global.ingress.tlsSecretName }}
      secretName: {{ $.Values.global.ingress.tlsSecretName }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
