{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "apis" -}}
{{- $values := .Values -}}
{{- $context := . -}}
apiVersion: {{ if $.Capabilities.APIVersions.Has "networking.k8s.io/v1" }}networking.k8s.io/v1{{ else }}extensions/v1beta1{{ end }}
kind: Ingress
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "tier" $tier ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier ) | nindent 4 }}
  annotations:
    {{ $.Values.global.ingress.annotationsPrefix}}/ssl-redirect: "false"
    {{ $.Values.global.ingress.annotationsPrefix}}/rewrite-target: /{{ $tier }}/$2
    {{ $.Values.global.ingress.annotationsPrefix}}/client-max-body-size: 1m
    {{ $.Values.global.ingress.annotationsPrefix}}/limit-rpm: "100"
    {{ $.Values.global.ingress.annotationsPrefix}}/limit-connections: "3"
    kubernetes.io/ingress.class: {{ $.Values.global.ingress.class}}
spec:
  rules:
    - host: {{ $.Values.global.ingress.host }}
      http:
        paths:
          - path: {{ if $.Values.global.ingress.root }}{{ $.Values.global.ingress.root }}{{- end }}/{{ $tier }}(/|$)(.*)
            backend:
              serviceName:  {{ include "bmrg.name" (dict "context" $context "tier" "services" "component" "workflow" ) }}
              servicePort: {{ $platform }}-port-svc
  tls:
    - hosts:
        - {{ $.Values.global.ingress.host }}
      {{- if $.Values.global.ingress.tlsSecretName }}
      secretName: {{ $.Values.global.ingress.tlsSecretName }}
      {{- end }}